name: Python Package Pull Request

on:
    pull_request:
        branches:
            - main
        paths-ignore:
            - "README.md"
            - "LICENSE"
            - "CONTRIBUTING.md"

jobs:
    ci:
        # Using 22.04 to be compatiable with Python 3.7 until it is deprecated
        runs-on: ubuntu-22.04
        strategy:
            matrix:
                python-version: [ 3.7, 3.8, 3.9]

        steps:
            - uses: actions/checkout@v4
            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v4
              with:
                  python-version: ${{ matrix.python-version }}

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements_dev.txt

            - name: Lint
              run: make lint

            - name: python vulnerability code scan
              run: make bandit

            - name: Test & Coverage
              run: make coverage-ci
